version: '3.8'

services:
  voice-lab-gpt:
    build: .
    container_name: voice-lab-gpt
    volumes:
      - ./examples:/app/examples
      - ./tests:/app/tests
      - ./reports:/app/reports
      - ./audio_samples:/app/audio_samples
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    command: python examples/basic_usage.py

  # Optional: Jupyter notebook for interactive analysis
  jupyter:
    build: .
    container_name: voice-lab-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    environment:
      - JUPYTER_ENABLE_LAB=yes